In [94]:
#Exp no.:10

In [95]:
#Aim:To perform a operation on simple linear regression

In [1]:
#Name:Pranita Sakarde
#Roll no.:51
#Sec:c
#Subject:DSS

In [97]:
#importing the basic library
import pandas as pd
import numpy as np

In [98]:
import os

In [99]:
os.getcwd()

'C:\\Users\\USER\\OneDrive\\Desktop'

In [100]:
os.chdir("C:\\Users\\USER\\OneDrive\\Desktop")

In [101]:
data=pd.read_csv("salary.csv")

In [102]:
data.head()

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [103]:
data.head(51)

    YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872
30             11.2  127345
31             11.5  126756
32             12.3  128765
33             12.9  135675
34             13.5  139465

In [104]:
data.tail()

    YearsExperience  Salary
30             11.2  127345
31             11.5  126756
32             12.3  128765
33             12.9  135675
34             13.5  139465

In [105]:
data.isna()

    YearsExperience  Salary
0             False   False
1             False   False
2             False   False
3             False   False
4             False   False
5             False   False
6             False   False
7             False   False
8             False   False
9             False   False
10            False   False
11            False   False
12            False   False
13            False   False
14            False   False
15            False   False
16            False   False
17            False   False
18            False   False
19            False   False
20            False   False
21            False   False
22            False   False
23            False   False
24            False   False
25            False   False
26            False   False
27            False   False
28            False   False
29            False   False
30            False   False
31            False   False
32            False   False
33            False   False
34            False   False

In [106]:
data.isna().any()

YearsExperience    False
Salary             False
dtype: bool

In [107]:
data.isna().sum()

YearsExperience    0
Salary             0
dtype: int64

In [108]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  35 non-null     float64
 1   Salary           35 non-null     int64
dtypes: float64(1), int64(1)
memory usage: 692.0 bytes

In [109]:
data.describe()

       YearsExperience         Salary
count        35.000000      35.000000
mean          6.308571   83945.600000
std           3.618610   32162.673003
min           1.100000   37731.000000
25%           3.450000   57019.000000
50%           5.300000   81363.000000
75%           9.250000  113223.500000
max          13.500000  139465.000000

In [110]:
data.ndim

2

In [111]:
data.shape

(35, 2)

In [112]:
data.size

70

Independent and dependent variable

In [113]:
X=data.drop('Salary',axis=1)

In [114]:
X.head()

   YearsExperience
0              1.1
1              1.3
2              1.5
3              2.0
4              2.2

In [115]:
Y=data.Salary

In [116]:
Y.head()

0    39343
1    46205
2    37731
3    43525
4    39891
Name: Salary, dtype: int64

In [117]:
from sklearn.model_selection import train_test_split

In [118]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=0,test_size=0.30)

In [119]:
print(X_train.shape)

(24, 1)

In [120]:
X_test.shape

(11, 1)

In [121]:
print(Y_train.shape)

(24,)

In [122]:
Y_test.shape

(11,)

In [123]:
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(X_train,Y_train)

LinearRegression()

In [124]:
m = LR.coef_

In [125]:
print("Coefficient  :" , m)

Coefficient  : [8528.00205699]

In [126]:
c = LR.intercept_

In [127]:
print("Intercept : ", c)

Intercept :  30653.80404187284

y=mx+c

prediction

In [128]:
Y_pred=LR.predict(X_test)

In [129]:
Y_pred

array([120197.8256403 ,  88644.21802942,  74146.61453254, 118492.2252289 ,
        98025.02029212,  72441.01412114,  63913.01206415,  43445.80712736,
        64765.81226984, 112522.623789  , 107405.82255481])

In [130]:
Y_test

29    121872
20     91738
16     66029
28    122391
22    101302
15     67938
10     63218
2      37731
11     55794
27    112635
25    105582
Name: Salary, dtype: int64

Evaluation metrices

In [131]:
from sklearn import metrics

ACCURACY

In [132]:
Accuracy = LR.score(X_test, Y_test)
Accuracy

0.9714499470616078

MAE

In [133]:
print(metrics.mean_absolute_error(Y_test,Y_pred))

3807.469971826513

MSE

In [134]:
print(np.sqrt(metrics.mean_squared_error(Y_test,Y_pred)))

4685.185783311836

RMSE

In [136]:
rmse = np.sqrt(metrics.mean_squared_error(Y_test,Y_pred))
print("RMSE:", rmse)

RMSE: 4685.185783311836